- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
  - install_directory: /opt/static-website-example
  tasks:
  - name: 'update website from the git repository'
    git:
      repo: "{{ githubRepo }}" 
      dest: "{{ install_directory }}"
  
